Repository metoop/Cache-Algorithms, pull requests merged in 2020-10, with the labels that each got.

#17 N-Queen algorithm's implimented in c++
  N-Queen.cpp
Labels: done

#18 Trie implimented
  Trie.cpp
Labels: done

#19 lfu-cache-added in java
  LFUCache.java
Labels: done

#20 LRUCache added in python language
  LRUCache.py
Labels: done

#24 task scheduler algorithm in python
  TaskScheduler.py
Labels: done

#25 lfu-cache implimented in c++
  LFUCache.cpp
Labels: done

#27 Implement LFUCache in JavaScript
  LFUCache.js
Labels: done

#28 trie implemented in javascript
  Trie.js
Labels: done

#29 N-Queen implement in javascript
  N-Queen.js
Labels: done

#30 lfu cahce added in python language
  LFUCache.py
Labels: done, hacktoberfest-accepted

#31 N-Queen added in java
  NQueen.java
Labels: hacktoberfest-accepted

#33 code beautified
  LFUCache.cpp
Labels: C++, enhancement, hacktoberfest-accepted

#34 code beautified
  LRUCache.cpp
Labels: enhancement, hacktoberfest-accepted
